### ISSUE TITLE
Personal task: Antonova

### ISSUE THREAD

**Issue by dkurt** [Teddy-Hackers/devtools-course-practice#147]
@AnastasyaAntonova, ваше задание:

1. Найти проект с 100 или более звёзд на GitHub
2. Подобрать задачу по силам в Issues. Иногда, можно ориентироваться на метки "good first issue" или "help wanted". Например:
    * https://github.com/opencv/opencv/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aclosed
    * https://github.com/opencv/opencv/issues?q=is%3Aissue+label%3A%22community+help+requested%22+is%3Aopen
3. Требуется сделать что-то реально полезное.
4. Выполнить задачу, открыть PR и добиться, чтобы его приняли (merged).

**Comment by AnastasyaAntonova** [comment]
Здравствуйте! Взяла задачку по переводу на русский язык статьи "Сохранение и сброс состояния" в React. Ссылка на 
PR: https://github.com/reactjs/ru.react.dev/pull/895
