### ISSUE TITLE
Personal task: Bochkarev

### ISSUE THREAD

**Issue by dkurt** [Teddy-Hackers/devtools-course-practice#150]
@TibidoX, ваше задание:

1. Найти проект с 100 или более звёзд на GitHub
2. Подобрать задачу по силам в Issues. Иногда, можно ориентироваться на метки "good first issue" или "help wanted". Например:
    * https://github.com/opencv/opencv/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aclosed
    * https://github.com/opencv/opencv/issues?q=is%3Aissue+label%3A%22community+help+requested%22+is%3Aopen
3. Требуется сделать что-то реально полезное.
4. Выполнить задачу, открыть PR и добиться, чтобы его приняли (merged).

**Comment by TibidoX** [comment]
https://github.com/reactjs/ru.react.dev/pull/884
