### ISSUE TITLE
Add accepted-with-delay badge

### ISSUE THREAD

**Issue by dkurt** [Teddy-Hackers/devtools-course-practice#66]
Add one more badge for https://teddy-hackers.github.io/devtools-course-practice
Badge: https://img.shields.io/badge/-accepted--with--delay-yellow

If PR was merged after the specific date:
```
lab1: 1 may, 2023
lab2: 15 may, 2023
lab3: 1 June, 2023
```

**Comment by akandrin** [comment]
@dkurt Здравствуйте. А на что будет влиять метка "accepted-with-delay"? Ранее вы говорили, что "сдать надо до начала зачётной сессии, но желательно сдавать в несколько этапов: конец апреля, середина мая, конец мая".

Какие будут последствия для студентов, которые не уложатся в "желательные" сроки?

**Comment by dkurt** [comment]
@akandrin, хороший вопрос

@eizamaliev, нам нужны такая отметка в таблице успеваемости?
